---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: podman
platforms:
  - name: ubuntu2204
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    pre_build_image: true
  - name: ubuntu2004
    groups:
      - openssl1
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    pre_build_image: true
  - name: debian12
    image: docker.io/geerlingguy/docker-debian12-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    pre_build_image: true
  - name: debian11
    groups:
      - openssl1
    image: docker.io/geerlingguy/docker-debian11-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    pre_build_image: true
  - name: fedora38
    image: docker.io/geerlingguy/docker-fedora38-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    pre_build_image: true
  - name: fedora37
    image: docker.io/geerlingguy/docker-fedora37-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    pre_build_image: true
  - name: centosstream9
    image: ghcr.io/bcook254/docker-centosstream9-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      openssl1:
    host_vars:
      centosstream9:
        vaultwarden_packages:
          - openssl
          - ca-certificates
          - curl-minimal
          - mariadb-devel
          - libpq
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: yaml
    ssh_connection:
      pipelining: false
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .