---
# Variable configuration.
- name: Include OS-specific variables (Debian).
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'Debian'

- name: Include OS-specific variables (RedHat).
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  when:
    - ansible_os_family == 'RedHat'

- name: Define vaultwarden_packages.
  ansible.builtin.set_fact:
    vaultwarden_packages: "{{ __vaultwarden_packages | list }}"
  when: vaultwarden_packages is not defined
