---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: podman
platforms:
  - name: ${PLATFORM_NAME:-ubuntu2404}
    image: ${PLATFORM_IMAGE:-"docker.io/geerlingguy/docker-ubuntu2404-ansible:latest"}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        vaultwarden_version: "${VAULTWARDEN_VERSION}"
        vaultwarden_url: "${VAULTWARDEN_URL}"
        vaultwarden_url_checksum: "sha256:{{ vaultwarden_url }}.sha256"
    host_vars:
      centosstream9:
        vaultwarden_packages:
          - openssl
          - ca-certificates
          - curl-minimal
          - mariadb-devel
          - libpq
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint .
