---
name: ci
'on':
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'meta/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Install test dependencies.
        run: python -m pip install yamllint

      - name: Lint code.
        run: yamllint .

  molecule:
    name: Molecule Test (${{ matrix.platform.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: ubuntu2404
            image: docker.io/geerlingguy/docker-ubuntu2404-ansible:latest
          - name: ubuntu2204
            image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
          - name: debian12
            image: docker.io/geerlingguy/docker-debian12-ansible:latest
          - name: fedora40
            image: docker.io/geerlingguy/docker-fedora40-ansible:latest
          - name: fedora39
            image: docker.io/geerlingguy/docker-fedora39-ansible:latest
          - name: fedora38
            image: docker.io/geerlingguy/docker-fedora38-ansible:latest
          - name: centosstream9
            image: ghcr.io/bcook254/docker-centosstream9-ansible:latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Install test dependencies.
        run: python -m pip install molecule molecule-plugins[docker]

      - name: Run Molecule tests.
        run: molecule test --driver-name docker
        env:
          PLATFORM_NAME: ${{ matrix.platform.name }}
          PLATFORM_IMAGE: ${{ matrix.platform.image }}
          VAULTWARDEN_VERSION: '1.30.5'
          VAULTWARDEN_URL: ${{ secrets.VAULTWARDEN_URL }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
